[features]
seeds = false
skip-lint = false

[programs.devnet]
soundchain = "Bnuq1snxvTd8oMVx1Spf588QoPUJmGxME5yYURawssmu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
